version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: game_master
      POSTGRES_PASSWORD: password
      POSTGRES_DB: python_text_game
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # app:
  #  build:
  #    context: .
  #  container_name: python_text_game_app
  #  environment:
  #    DATABASE_URL: postgresql+psycopg2://user:password@db:5432/python_text_game
  #  depends_on:
  #    - db
  #  stdin_open: true  # Keep the container open for interactive input
  #  tty: true         # Allocate a pseudo-TTY for the console app

volumes:
  db_data: